#require 'active_support'
require 'action_view' # /template/handlers/erb'

module E16Theme
  class KwinQmlRenderer < BaseRenderer

    def write_contents
      File.open("#{common_install_path}/#{dir_name}/metadata.desktop", "wb+") do |f|
        f.write metadata_desktop_content
      end
      File.open("#{common_install_path}/#{dir_name}/contents/config/main.xml", "wb+") do |f|
        f.write main_xml_content
      end
      File.open("#{common_install_path}/#{dir_name}/contents/ui/main.qml", "wb+") do |f|
        f.write main_qml_content
      end
    end

    def metadata_desktop_content
      template = File.read("#{templates_folder}/metadata.desktop.erb")
      ERB.new(template).result(template_variables)
    end

    def main_xml_content
      template = File.read("#{templates_folder}/main.xml.erb")
      ERB.new(template).result(template_variables)
    end

    def main_qml_content
      template = File.read("#{templates_folder}/main.qml.erb")
      ERB.new(template).result(template_variables)
    end

    def template_variables
      OpenStruct.new(
        theme_name: theme_name,
        theme_name_downcase: theme_name.downcase,
        comment: "Imported theme from E16 collection - Converted for KDE/kwin",
        author: "AutoGenerated by Mathieu Jobin (somekool) - original author see AUTHOR file.",
        email: "opensource@somekool.net",
        license: "Free - see LICENSE file for original theme license.",
        border_size_left: parser.border_definitions[:default_definition][:border_size_left],
        border_size_right: parser.border_definitions[:default_definition][:border_size_right],
        border_size_top: parser.border_definitions[:default_definition][:border_size_top],
        border_size_bottom: parser.border_definitions[:default_definition][:border_size_bottom],
        parser: parser,
        parts: parser.border_definitions[:default_definition][:parts],
        theme_path: theme_path,
        mode: mode
      ).instance_eval { binding }
    end

    def dir_name
      "kwin4_decoration_qml_#{theme_name}"
    end

    def common_install_path
      "/usr/share/kwin/decorations/"
    end

    def templates_folder
      "#{__dir__}/qml_templates"
    end
  end
end
