# these shall be ignored forever ...
module E16Theme
  module WidgetStyling
    BUTTON_BLACK=:BUTTON_BLACK
    COORDS=:COORDS
    DIALOG=:DIALOG
    DIALOG_BUTTON=:DIALOG_BUTTON
    DIALOG_WIDGET_BUTTON=:DIALOG_BUTTON
    DIALOG_WIDGET_CHECK_BUTTON=:DIALOG_BUTTON
    DIALOG_WIDGET_RADIO_BUTTON=:DIALOG_BUTTON
    DIALOG_WIDGET_SEPARATOR=:DIALOG_WIDGET_SEPARATOR
    DIALOG_WIDGET_TABLE=:DIALOG_WIDGET_TABLE
    DIALOG_WIDGET_AREA=:DIALOG_WIDGET_AREA
    DIALOG_WIDGET_SLIDER_BASE_HORIZONTAL=:DIALOG_WIDGET_SLIDER
    DIALOG_WIDGET_SLIDER_BASE_VERTICAL=:DIALOG_WIDGET_SLIDER
    DIALOG_WIDGET_SLIDER_KNOB_VERTICAL=:DIALOG_WIDGET_SLIDER
    DIALOG_WIDGET_SLIDER_KNOB_HORIZONTAL=:DIALOG_WIDGET_SLIDER

    SETTINGS_DESKTOP_AREA=:SETTINGS_DESKTOP
    SETTINGS_AREA_AREA=:SETTINGS_DESKTOP
    SETTINGS_AREADESK_AREA=:SETTINGS_DESKTOP

    DESKTOP_DRAGBUTTON_HORIZ=:dragbar
    DESKTOP_DRAGBUTTON_VERT=:dragbar
    DESKTOP_RAISEBUTTON_HORIZ=:raise_button
    DESKTOP_RAISEBUTTON_VERT=:raise_button
    DESKTOP_LOWERBUTTON_HORIZ=:lower_button
    DESKTOP_LOWERBUTTON_VERT=:lower_button
    DESKTOP_DESKRAY_HORIZ=:deskray
    DESKTOP_DESKRAY_VERT=:deskray

    EPPLET_BACKGROUND_HORIZONTAL=:epplet
    EPPLET_BACKGROUND_VERTICAL=:epplet
    EPPLET_BUTTON=:epplet
    EPPLET_TOGGLEBUTTON_OFF=:epplet
    EPPLET_TOGGLEBUTTON_ON=:epplet
    EPPLET_DRAWINGAREA=:epplet
    EPPLET_HSLIDER_BASE=:epplet
    EPPLET_HSLIDER_KNOB=:epplet
    EPPLET_VSLIDER_BASE=:epplet
    EPPLET_VSLIDER_KNOB=:epplet
    EPPLET_POPUP_BASE=:epplet
    EPPLET_POPUP_ENTRY=:epplet
    EPPLET_HBAR_BASE=:epplet
    EPPLET_HBAR_BAR=:epplet
    EPPLET_VBAR_BASE=:epplet
    EPPLET_VBAR_BAR=:epplet
    EPPLET_ARROW_UP=:epplet
    EPPLET_ARROW_DOWN=:epplet
    EPPLET_ARROW_LEFT=:epplet
    EPPLET_ARROW_RIGHT=:epplet
    EPPLET_PLAY=:epplet
    EPPLET_STOP=:epplet
    EPPLET_PAUSE=:epplet
    EPPLET_PREVIOUS=:epplet
    EPPLET_NEXT=:epplet
    EPPLET_EJECT=:epplet
    EPPLET_CLOSE=:epplet
    EPPLET_FAST_FORWARD=:epplet
    EPPLET_REWIND=:epplet
    EPPLET_REPEAT=:epplet
    EPPLET_SKIP=:epplet
    EPPLET_HELP=:epplet
    EPPLET_CONFIGURE=:epplet
    WARPFOCUS=:epplet

    ICONBOX_HORIZONTAL=:iconbox
    ICONBOX_VERTICAL=:iconbox
    ICONBOX_COVER_VERTICAL=:iconbox
    ICONBOX_COVER_HORIZONTAL=:iconbox
    ICONBOX_ARROW_LEFT=:iconbox
    ICONBOX_ARROW_RIGHT=:iconbox
    ICONBOX_ARROW_UP=:iconbox
    ICONBOX_ARROW_DOWN=:iconbox
    ICONBOX_SCROLLBAR_BASE_HORIZONTAL=:iconbox
    ICONBOX_SCROLLBAR_KNOB_HORIZONTAL=:iconbox
    ICONBOX_SCROLLBAR_BASE_VERTICAL=:iconbox
    ICONBOX_SCROLLBAR_KNOB_VERTICAL=:iconbox

    DEFAULT_ICON_BUTTON=:default_icon_button

    MENU_BG=:rootmenu_bg
    MENU_SUB=:rootmenu_sub
    MENU_SEL=:rootmenu_sel

    PAGER_WIN=:pager_win
    PAGER_BACKGROUND=:pager_bg
    PAGER_SEL=:pager_sel

    TT_MAIN=:tooltip_main
    TT_MINI=:tooltip_mini
    TT_BLANK=:tooltip_blank
    TT_CLOUD1=:tooltip_cloud1
    TT_CLOUD2=:tooltip_cloud2
    TT_CLOUD3=:tooltip_cloud3
    TT_CLOUD4=:tooltip_cloud4
  end
end
